dinner = """| **Recipe Name**                                  | **Calories** | **Protein (g)** | **Carbs (g)** | **Fat (g)** | **Fibre (g)** | **Ingredients (with quantities)**                                                                                      | **Method**                                                                                             |
| ------------------------------------------------ | ------------ | --------------- | ------------- | ----------- | ------------- | ---------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------ |
| **Lemon Herb Chicken with Rice & Greens**        | 480          | 38              | 35            | 18          | 6             | 120g grilled chicken breast, 80g cooked jasmine rice, 50g sautéed spinach, 1 tbsp garlic-infused oil, juice of ½ lemon | Marinate chicken in lemon and herbs, grill. Serve with rice and sautéed spinach in garlic-infused oil. |
| **Grilled Salmon & Roasted Veggies**             | 500          | 34              | 25            | 30          | 5             | 120g salmon fillet, 100g roasted carrots and zucchini, 1 tsp olive oil, lemon wedge                                    | Roast veg at 200°C for 25 mins. Grill salmon with lemon and oil. Serve together.                       |
| **Low FODMAP Stir Fry with Tofu & Rice Noodles** | 470          | 20              | 50            | 18          | 7             | 100g firm tofu, 80g cooked rice noodles, 50g bok choy, 40g carrots, 1 tbsp garlic-infused oil, tamari                  | Stir-fry tofu in oil, add veggies and tamari. Add noodles, cook until heated.                          |
| **Turkey & Zucchini Patties with Mash**          | 460          | 35              | 30            | 20          | 6             | 120g lean ground turkey, 50g grated zucchini, 1 egg, herbs, 100g mashed potato (plain), 1 tsp olive oil                | Mix turkey, zucchini, and egg. Form patties and pan-fry. Serve with mash and greens.                   |
| **Tempeh & Quinoa Power Bowl**                   | 490          | 28              | 40            | 22          | 8             | 100g tempeh, 80g cooked quinoa, 50g sautéed spinach, 40g roasted pumpkin, 1 tsp sesame oil                             | Roast pumpkin, sauté spinach. Pan-fry tempeh and serve all together with quinoa.                       |
"""
lunch = """| **Recipe Name**                     | **Calories** | **Protein (g)** | **Carbs (g)** | **Fat (g)** | **Fibre (g)** | **Ingredients (quantities)**                                                                                                                 | **Method**                                                                                      |
| ----------------------------------- | ------------ | --------------- | ------------- | ----------- | ------------- | -------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------- |
| **Tuna & Quinoa Salad Bowl**        | 410          | 30              | 35            | 14          | 7             | 90g cooked quinoa, 80g canned tuna (drained), 50g spinach (raw), 50g red bell pepper (raw), 1 tbsp olive oil (10g), lemon juice              | Mix quinoa, tuna, chopped veg, olive oil and lemon juice. Chill and store in container.         |
| **Egg & Roasted Veggie Box**        | 440          | 22              | 30            | 24          | 8             | 2 boiled eggs (100g), 100g roasted carrots & zucchini (combined), 70g cooked white rice, 1 tsp olive oil                                     | Roast veg at 200°C for 20 mins. Combine with rice and sliced eggs. Drizzle with olive oil.      |
| **Tempeh Quinoa Stir-Fry (Cold)**   | 450          | 26              | 40            | 18          | 9             | 80g cooked quinoa, 80g tempeh (lightly pan-fried), 50g carrots, 40g baby spinach, 1 tbsp garlic-infused oil (no garlic solids)               | Stir-fry tempeh and veg with garlic-infused oil, mix with quinoa. Serve warm or cold.           |
| **Crispy Tofu & Rice Salad**        | 470          | 25              | 45            | 20          | 10            | 100g firm tofu (pan-fried), 70g cooked jasmine rice, 40g grated carrots, 40g cucumber (peeled), 1 tbsp tamari, 1 tsp sesame oil              | Fry tofu cubes, mix with rice and veg, drizzle with sesame oil and tamari. Cool before packing. |
| **Chicken & Roasted Pumpkin Salad** | 480          | 35              | 30            | 18          | 7             | 100g grilled chicken breast, 100g roasted pumpkin (cubed), 40g baby spinach, 1 tbsp olive oil, 1 tbsp pumpkin seeds (optional, if tolerated) | Roast pumpkin, mix with sliced chicken and spinach. Drizzle oil before serving.                 |
"""
snack = """| **Snack Name**                          | **Calories** | **Protein (g)** | **Carbs (g)** | **Fat (g)** | **Fibre (g)** | **Ingredients (with quantities)**                                                                         | **Method**                                                                    |
| --------------------------------------- | ------------ | --------------- | ------------- | ----------- | ------------- | --------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- |
| **Cottage Cheese & Blueberries**        | 170          | 14              | 12            | 6           | 2             | 100g lactose-free cottage cheese, 50g blueberries                                                         | Scoop cottage cheese into container, top with berries. Chill.                 |
| **Oat & Sunflower Seed Bar (Homemade)** | 200          | 4               | 28            | 8           | 4             | 40g rolled oats (dry), 10g sunflower seeds, 1 tbsp maple syrup, 2 tbsp applesauce, 1 tsp coconut oil      | Mix and press into tray. Bake at 180°C for 15–20 min. Cool and slice.         |
| **Carrot Sticks & Hummus (Low FODMAP)** | 220          | 6               | 20            | 12          | 6             | 80g carrots (raw sticks), 40g homemade low-FODMAP hummus (from canned lentils, garlic-infused oil, lemon) | Portion hummus into a small container. Add carrot sticks. Keep chilled.       |
| **Lactose-Free Yogurt & Kiwi**          | 180          | 8               | 20            | 7           | 3             | 125g lactose-free yogurt, 1 small kiwi (peeled & sliced)                                                  | Combine yogurt and kiwi in portable container. Optional: sprinkle with chia.  |
| **Boiled Egg & Cherry Tomatoes**        | 150          | 12              | 4             | 9           | 1             | 1 boiled egg (50g), 60g cherry tomatoes                                                                   | Slice egg and pack with halved tomatoes. Add pinch of salt/pepper if desired. |
"""