dinner = """
| NAME                                            | CALORIES | PROTEIN (g) | FAT (g) | CARBS (g) | FIBRE (g) | INGREDIENTS                                                                                                                                                                         | METHOD                                                                                                        |
| --------------------------------------------------- | ------------ | --------------- | ----------- | ------------- | ------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------- |
| Grilled Lemon Chicken with Quinoa & Roasted Veg | 580          | 34              | 21          | 42            | 7             | - 120g grilled chicken breast (cooked)  <br> - 90g cooked quinoa  <br> - 60g roasted carrots & zucchini (raw weight)  <br> - 1 tbsp garlic-infused olive oil  <br> - Juice of ½ lemon   | Roast veg with garlic oil (200°C, 25 mins). Grill chicken. Serve with quinoa and lemon juice.                     |
| Pan-Fried Salmon with Mashed Potato & Greens    | 590          | 32              | 31          | 32            | 6             | - 120g salmon fillet (raw) <br> - 150g boiled potatoes (peeled, cooked) <br> - 50g steamed spinach <br> - 1 tsp olive oil <br> - 1 tsp butter <br> - Salt, lemon wedge                  | Boil potatoes and mash with butter. Steam spinach. Pan-fry salmon in oil. Serve all warm with lemon.              |
| Beef & Rice Stuffed Peppers                     | 560          | 33              | 22          | 44            | 7             | - 100g lean ground beef (5% fat, raw) <br> - 80g cooked white rice <br> - 1 red bell pepper (100g) <br> - 1 tbsp garlic-infused oil <br> - 20g grated lactose-free cheese               | Sauté beef in garlic oil. Mix with rice and cheese. Stuff into halved peppers. Bake at 180°C for 25 mins.         |
| Baked Tempeh with Roasted Pumpkin & Millet      | 575          | 30              | 25          | 45            | 8             | - 100g tempeh (plain) <br> - 90g cooked millet <br> - 80g roasted pumpkin (peeled, raw weight) <br> - 1 tbsp garlic-infused oil <br> - ½ tsp paprika                                    | Cube and bake pumpkin (200°C, 30 mins). Pan-fry tempeh. Serve all with millet and oil drizzle.                    |
| Turkey Meatballs with Pasta & Zucchini          | 600          | 35              | 18          | 50            | 7             | - 120g lean turkey mince (raw) <br> - 80g cooked gluten-free pasta <br> - 80g zucchini (spiralised or chopped) <br> - 1 tbsp garlic-infused oil <br> - 1 tbsp lactose-free cream cheese | Mix mince with herbs, form 4–5 meatballs, pan-fry. Boil pasta, sauté zucchini. Combine with cream cheese to coat. |
"""
lunch = """
| NAME                             | CALORIES | PROTEIN (g) | FAT (g) | CARBS (g) | FIBRE (g) | INGREDIENTS                                                                                                                                                                  | METHOD                                                                                                     |
| ------------------------------------ | ------------ | --------------- | ----------- | ------------- | ------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| Grilled Chicken & Quinoa Salad   | 480          | 30              | 18          | 35            | 7             | - 120g grilled chicken breast (cooked)  <br> - 80g cooked quinoa <br> - 50g baby spinach (raw) <br> - ½ red pepper (40g, raw) <br> - 1 tbsp garlic-infused olive oil <br> - 1 tbsp lemon juice     | Combine cooked chicken, quinoa, chopped red pepper, and spinach. Drizzle with oil and lemon. Chill for office. |
| Low FODMAP Tuna Rice Bowl        | 470          | 28              | 17          | 40            | 6             | - 1 tin tuna in spring water (100g drained) <br> - 100g cooked white rice <br> - 50g grated carrot <br> - 50g cucumber (sliced) <br> - 1 tbsp garlic-infused olive oil <br> - 1 tbsp soy-free mayo | Mix tuna with mayo. Serve over rice and veg. Drizzle oil over top.                                             |
| Egg & Roasted Veg Frittata       | 460          | 26              | 22          | 22            | 7             | - 3 large eggs <br> - 100g roasted zucchini, carrots, red pepper <br> - 30g lactose-free cheese <br> - 1 tsp olive oil                                                                             | Whisk eggs, mix in veg and cheese. Bake at 180°C in greased tin for 20–25 mins. Slice and chill.               |
| Turkey, Spinach & Rice Wrap (GF) | 500          | 29              | 20          | 40            | 6             | - 90g cooked lean turkey mince <br> - 1 large gluten-free wrap (\~50g) <br> - 50g baby spinach <br> - 1 tbsp garlic-infused oil <br> - 2 tbsp lactose-free plain yogurt                            | Sauté turkey in garlic oil. Fill wrap with turkey, spinach, yogurt. Fold tightly and wrap in foil.             |
| Tofu & Buckwheat Noodle Stir Fry | 495          | 25              | 18          | 45            | 8             | - 100g firm tofu (pressed, cooked) <br> - 80g cooked buckwheat noodles <br> - 50g bok choy <br> - 40g carrots <br> - 1 tbsp sesame oil <br> - 1 tbsp tamari                                        | Stir-fry tofu and veg in sesame oil. Add noodles and tamari. Mix and chill.                                    |
"""
snack = """
| NAME                             | CALORIES | PROTEIN (g) | FAT (g) | CARBS (g) | FIBRE (g) | INGREDIENTS                                                                                                                                         | METHOD                                                                                     |
| ------------------------------------ | ------------ | --------------- | ----------- | ------------- | ------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------- |
| Rice Cakes with Egg & Avocado    | 220          | 10              | 11          | 18            | 4             | - 1 boiled egg <br> - 2 plain rice cakes <br> - ¼ avocado (mashed, ~30g)                                                                                | Boil egg, cool and slice. Spread mashed avocado on rice cakes. Top with egg slices.             |
| Boiled Egg & Rice Cake Duo       | 215          | 12              | 12          | 14            | 1.5           | - 1 large boiled egg <br> - 2 plain rice cakes <br> - 1 tsp lactose-free butter (optional)                                                              | Boil egg, cool and peel. Serve with rice cakes and optional spread.                            |
| Lactose-Free Greek Yogurt + Chia | 240          | 13              | 10          | 19            | 4             | - 130g lactose-free plain Greek yogurt <br> - 1 tsp chia seeds (5g) <br> - ¼ banana (if tolerated – \~25g)                                              | Mix yogurt with chia seeds. Add thin banana slices. Chill for 15 min if possible.              |
| Homemade Oat Bar & Kiwi          | 245          | 9               | 10          | 32            | 3.5           | - 1 homemade oat bar (\~40g) <br> - 1 kiwi (peeled, \~75g)                                                                                              | Bake oat bar in advance (from your earlier recipe), slice and pair with fresh kiwi.            |
| Mini Tofu Veg Box                | 250          | 15              | 13          | 15            | 3             | - 80g firm tofu (pressed, cooked) <br> - 50g cucumber (raw, sliced) <br> - 1 tsp garlic-infused olive oil <br> - 1 tsp tamari <br> - 1 tsp sesame seeds | Slice tofu into cubes. Toss with oil and tamari. Add cucumber and sesame seeds. Serve chilled. |
"""
breakfast = """
| NAME                                | CALORIES | PROTEIN (g) | FAT (g) | CARBS (g) | FIBRE (g) | INGREDIENTS                                                                                                                                    | METHOD                                                                                           |
| ----------------------------------- | ------------ | --------------- | ----------- | ------------- | ------------- | -------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------- |
| Oat Chia Yogurt Pot                 | 285          | 13              | 9           | 35            | 6             | - 130g lactose-free Greek yogurt <br> - 20g dry rolled oats <br> - 1 tsp chia seeds (5g) <br> - ½ kiwi (peeled, 35g)                               | Mix oats and chia into yogurt. Top with kiwi slices. Let sit 10+ mins or overnight.                  |
| Egg & Seed Crackers                 | 260          | 13              | 15          | 16            | 4.5           | - 2 boiled eggs <br> - 2 seed-based crackers (e.g. linseed, 20g total)                                                                             | Slice eggs. Serve with crackers. Optional sprinkle of salt or paprika.                               |
| Tofu Berry Smoothie                 | 295          | 14              | 10          | 32            | 5             | - 100g silken tofu <br> - 80g frozen mixed berries (low FODMAP portion) <br> - 100ml oat milk (unsweetened) <br> - 1 tsp chia seeds (5g)           | Blend all ingredients until smooth. Chill and drink fresh.                                           |
| Strawberry Yogurt Bowl with Flax   | 275          | 14              | 9           | 25            | 5             | - 130g lactose-free Greek yogurt <br> - 100g fresh strawberries (sliced) <br> - 1 tsp ground flaxseed (5g)                                         | Mix together or layer in a jar. Eat chilled. Flax adds fibre & omega-3s.                             |
| Mini Savoury Chickpea Pancake       | 290          | 13              | 10          | 30            | 6             | - 40g chickpea flour (dry) <br> - 50ml water <br> - ½ tsp cumin <br> - Pinch salt <br> - 50g grated zucchini (squeezed dry) <br> - 1 tsp olive oil | Mix flour, water, spices, and zucchini. Fry in oil like a pancake, ~3 mins each side. Cool & slice. |
"""